INSERT INTO Motherboard_HICO69 VALUES ('SENYA')
INSERT INTO CPU_HICO69 VALUES ('SENYA1')
INSERT INTO RAM_HICO69 VALUES ('SENYA2')
INSERT INTO GPU_HICO69 VALUES ('SENYA3')
INSERT INTO Storage_HICO69 VALUES ('SENYA4','BLAT')
INSERT INTO PowerUnit_HICO69 VALUES ('SENYA5')
INSERT INTO Body_HICO69 VALUES ('SENYA6')

INSERT INTO Comp_HICO69 VALUES(2,2,2,2,2,2,2)
SELECT Motherboard_HICO69.Motherboard,CPU_HICO69.CPU,RAM_HICO69.RAM,GPU_HICO69.GPU,Storage_HICO69.HDD,Storage_HICO69.SSD,PowerUnit_HICO69.PowerUnit,Body_HICO69.Body FROM Comp_HICO69
	JOIN Motherboard_HICO69 ON Comp_HICO69.Motherboard = Motherboard_HICO69.ID
	JOIN CPU_HICO69 ON Comp_HICO69.CPU = CPU_HICO69.ID
	JOIN RAM_HICO69 ON Comp_HICO69.RAM = RAM_HICO69.ID
	JOIN GPU_HICO69 ON Comp_HICO69.GPU = GPU_HICO69.ID
	JOIN PowerUnit_HICO69 ON Comp_HICO69.PowerUnit = PowerUnit_HICO69.ID
	JOIN Body_HICO69 ON Comp_HICO69.Body = Body_HICO69.ID
	JOIN Storage_HICO69 ON Comp_HICO69.Storage = Storage_HICO69.ID

